export const projects = [
  {
    title: 'Plailister',
    job: 'Full Stack Developer',
    description:
      "Plailister is a SAAS for a music label 'Place Called Home'. I worked hand-in-hand with the data engineers. This SAAS displays Spotify's data and predict how their playlists, songs, campaigns might work. \nPlailister was developed using Next.JS, deployed on Vercel. MUI was used to build the components. \nA requested feature was to implement a dark & light mode. The main challenge of this project was performance: the team had many complicated algorithms to analyze their heavy data, if needed to be user-friendly, and fast, managing the data in the best way possible was everyday's task, and the team is happy with it.",
    tools: [
      'Next.JS',
      'React.JS',
      'Firebase',
      'MUI',
      'Vercel',
      'SAAS',
      'Rest API',
      'Apex Charts',
    ],
    link: '',
    caroussel: [
      `/images/plailister/home.png`,
      `/images/plailister/homedark.png`,
      `/images/plailister/search.png`,
      // `/images/plailister/playlist.png`,
      // `/images/plailister/takeover.png`,
      `/images/plailister/health.png`,
      `/images/plailister/grid.png`,
      `/images/plailister/carou.png`,
      `/images/plailister/follow.png`,
    ],
  },
  {
    title: 'Arkive-Portal',
    job: 'Full Stack Developer',
    description:
      'Arkive is cosmetic company working on circular economy. They needed a web app to allow their users to upload and track their products. I worked on this project as lead full stack developer, alonside the CTO / data engineer. \nArkive-Portal was developed using Next.JS, deployed on Vercel, managing users through firebase, and using Shopify as CMS. Main features were an emailing system, uploading data and viewing it though a dashboard.',
    tools: [
      'Next.JS',
      'React.JS',
      'Typescript',
      'Firebase',
      'MUI',
      'Vercel',
      'Shopify CMS',
      'Rest API',
    ],
    link: 'https://arkivegroup.com/',
    caroussel: [],
  },
  {
    title: 'Pit-Stat',
    job: 'Full Stack Developer',
    description:
      'Pit-Stat is a side-project, a Formula 1 dashboard, that I am currently working on. I am building it to learn new technologies, such as 3D, animations, various styling techniques. I use this project to learn about using and building my own APIs through Python and the FastAPI framework.',
    tools: [
      'Next.JS',
      'React.JS',
      'Typescript',
      'Python',
      'FastAPI',
      'Tailwind',
      'Framer Motion',
      'Firebase',
      'Rest API',
    ],
    link: '',
    caroussel: [],
  },
  {
    title: 'Cosy Jet Sessions',
    job: 'Full Stack Developer',
    description:
      'I am a co-founder of @cosyjetsessions, a digital music plateform. I am currently building a B2B webiste, a vitrine page, to display our content. I work on it in my spare time. I use this project to learn new technologies such as 3D, animations, various styling techniques. I used many different APIs (from google, youtube, spotify,...). \nCosy Jet Sessions is developed using Next.JS, a Postgresql database, and deployed on Vercel.',
    tools: [
      'Next.JS',
      'React.JS',
      'Typescript',
      'SASS',
      'Tailwind',
      'Framer Motion',
      'Firebase',
      'Rest API',
    ],
    link: 'https://www.cosyroom.be',
    caroussel: [],
  },
  {
    title: 'This Portfolio',
    job: 'Frontend Developer',
    description:
      'My portfolio was at first really simple, straightforward. The portfolio project was my playground to work on new technologies that I had just learnt. Also, It allows me to have a bit of fun while trying to do some effects. I built it first with simple Vanilla Javascript, then moved on to a Next.JS application, using Tailwind & SCSS for design, and Framer-Motion for animations. I deployed it to Github Pages, using Github Actions.',
    tools: [
      'Next.JS',
      'React.JS',
      'SASS',
      'Tailwind',
      'Framer Motion',
      'Github Pages',
    ],
    link: '',
    caroussel: [],
  },
  {
    title: 'Foodie Planner',
    job: 'Full Stack Developer',
    description:
      "Foodie Planner is a website we developed during the last two weeks of the bootcamp. Its purpose is to let the user get inspired with recipes, plan meals in his calendar, and generate a grocery list. \nFoodie Planner was developed using the 'Ruby on Rails' framework, and  then deployed to production through Heroku. \nDuring this project I learnt a lot about team work, efficient organization amd management of skills result in good results, after two weeks we were proud of all we had done in that short time, even though we wished we could have had time to add many more features. \nIn my spare time, I went back to this projects and I am rebuildinb it using Javascript only.",
    tools: [
      'Ruby on Rails',
      'Javascript',
      'SASS',
      'Bootstrap',
      'Heroku',
      'Postgresql',
      'Rest API',
    ],
    link: '',
    caroussel: [],
  },
]
